load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

native_binary(
    name = "buildifier",
    src = "@buildifier//file",
    out = "buildifier_copy",
    visibility = ["//visibility:public"],
)
