alias(
    name = "clang-format",
    actual = "@llvm//:clang-format",
    visibility = ["//visibility:public"],
)

alias(
    name = "clang-tidy",
    actual = "@llvm//:clang-tidy",
    visibility = ["//visibility:public"],
)

py_binary(
    name = "clang_format_wrapper",
    srcs = ["clang_format_wrapper.py"],
    visibility = ["//visibility:public"],
)
