alias(
    name = "clang-format",
    actual = "@llvm//:clang-format",
    visibility = ["//visibility:public"],
)

alias(
    name = "clang-tidy",
    actual = "@llvm//:clang-tidy",
    visibility = ["//visibility:public"],
)
